## YAML Template.
zuul:
  ignoredServices: '*'
  prefix: /admin
  routes:
    user:
      path: /user/**
      serviceId: user-services
    city:
      path: /city/**
      serviceId: city-services
    vlist:
      path: /vlist/**
      serviceId: value-list-services
      
server:
  port: 8086   # HTTP (Tomcat) port
  
# Spring properties
spring:
  application:
     name: admin-gateway  # Service registers under this name
      
# Discovery Server Access
eureka:
    instance:
        lease-renewal-interval-in-seconds: 1
        prefer-ip-address: true
#   metadata-map:
#     instance-id: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${random.value}}}
        metadata-map:
            instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    client:
        registerWithEureka: true
        serviceUrl:
            defaultZone: http://localhost:1111/eureka/

     
info:
  component: Admin Gateway
 
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 90000

ribbon:
## Max number of retries on the same server (excluding the first try)
  maxAutoRetries: 1
## Max number of next servers to retry (excluding the first server)
  MaxAutoRetriesNextServer: 2
## Connect timeout used by Apache HttpClient
  ConnectTimeout: 80000
## Read timeout used by Apache HttpClient
  ReadTimeout: 80000
