## YAML Template.
# Configure this Discovery Server
eureka:
 instance:
    hostname: localhost
 client:
   registerWithEureka: false
   fetchRegistry: false
 server:
   waitTimeInMsWhenSyncEmpty: 0
 
server:
  port: 1111   # HTTP (Tomcat) port
 
# Discovery Server Dashboard uses FreeMarker.  Don't want Thymeleaf templates
spring:
  thymeleaf:
    enabled: false     # Disable Thymeleaf
  application:
    name: eureka-server
#  cloud:
#    config:
#      uri: http://localhost:8888
#      fail-fast: true